### DISCUSSION TITLE
not able to deploy n8n oci chart via argocd

### DISCUSSION THREAD

**Discussion by kumari-shubham** [8gears/n8n-helm-chart#106] [General]
error:
```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `kustomize build <path to cached source>/staging/n8n-cluster --enable-helm` failed exit status 1: Error: Error: could not find protocol handler for: : unable to run: 'helm pull --untar --untardir <path to cached source>/staging/n8n-cluster/charts --repo 8gears.container-registry.com/library/n8n n8n --version 0.23.1' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-1677674532/helm HELM_CACHE_HOME=/tmp/kustomize-helm-1677674532/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-1677674532/helm/.data] (is 'helm' installed?): exit status 1
```

secret in argocd 
```
apiVersion: v1
kind: Secret
metadata:
  name: my-oci-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: n8n-oci-repo
  url: 8gears.container-registry.com/library/n8n
  enableOCI: "true"
  type: helm
  ForceHttpBasicAuth: "true"
```

using this helm chart
```
helmCharts:
  - name: n8n
    releaseName: n8n-cluster
    repo: 8gears.container-registry.com/library/n8n
    valuesFile: values.yaml
    version: 0.23.1
```

**Comment by dadangnh** [comment]
Hi, I am able to deploy it on argocd using the following manifest:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gke-cluster
  source:
    chart: n8n
    repoURL: 8gears.container-registry.com/library
    targetRevision: 0.25.2
    helm:
      releaseName: n8n
      valueFiles:
        - secrets+age-import:///helm-keys/key.txt?https://raw.githubusercontent.com/user/argocd/n8n/secrets.enc.yaml
      valuesObject:
        fullnameOverride: n8n
        extraEnv:
          WEBHOOK_URL: https://<the-n8n-address>
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 5
          targetCPUUtilizationPercentage: 60
        scaling:
          enabled: true
        redis:
          enabled: true
        service:
          type: ClusterIP
          port: 80
  destination:
    name: in-cluster
    namespace: n8n
  syncPolicy:
    automated:
      selfHeal: true
```

Please notice that on my manifest, I encrypted the n8n secrets using [SOPS](https://github.com/getsops/sops) + [rage](https://github.com/str4d/rage). The encrypted file will be executed as helm values to the chart.
