### DISCUSSION TITLE
Unable to install Helm chart

### DISCUSSION THREAD

**Discussion by ganesshwankhede** [8gears/n8n-helm-chart#137] [General]
Hello team,
Here are the steps I am doing 

`helm upgrade --install n8n -f values.yaml -n n8n oci://8gears.container-registry.com/library/n8n --version 0.25.2`

Here is my values.yaml
````
config:
  database:
    type: postgresdb
    postgresdb:
      host: dbhost.com
      user: postgres

secret:
  database:
    postgresdb:
      password: "postgresdbass"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: n8n.mydomain.com
      paths:
        - path: /
  tls:
    - secretName: ssl-cert-secret
      hosts:
        - n8n.mydomain.com

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

persistence:
  enabled: false
  type: emptyDir

replicaCount: 1

image:
  repository: n8nio/n8n
  pullPolicy: IfNotPresent
  tag: ""  # Default to latest stable version

serviceAccount:
  create: false
  annotations: {}
  name: ""

securityContext: {}

podSecurityContext: {}

imagePullSecrets: []

podAnnotations: {}
`
```


Below is the error I see

Error: UPGRADE FAILED: failed to create resource: Ingress.networking.k8s.io "n8n" is invalid: spec.rules[0].http.paths[0].path: Invalid value: "map[path:/ pathType:ImplementationSpecific]": must be an absolute path

and pods are showing 
DatabaseError: no pg_hba.conf entry for host "172.31.16.113", user "postgres", database "n8n", no encryption

**Comment by ganesshwankhede** [comment]
Also can someone share sample values.yaml 
for postgresdb and ingress with EKS ? 

CC: @Vad1mo

**Comment by meursong** [comment]
Hi @ganesshwankhede,

Did you manage to fix this issue? I'm facing the exact same error when trying to install the chart with my Ingress config:

Error: UPGRADE FAILED: failed to create resource: Ingress.networking.k8s.io "n8n" is invalid: spec.rules[0].http.paths[0].path: Invalid value: "map[path:/ pathType:Prefix]": must be an absolute path

My values.yaml is similar to yours:

```yaml
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: my.domain.com
      paths:
        - path: "/"  (or / i tried the both)
          pathType: Prefix
  tls:
    - hosts:
        - my.domain.com
      secretName: my-ssl
```

**Reply by meursong** [reply]
If there is anyone who is still struggling with the same issue, I was able to fix it like this
Instead of:

```yaml
paths:
  - path: "/"
    pathType: Prefix
```
I used:

```yaml
paths:
  - /
```

Hope it helps!
