### DISCUSSION TITLE
Trouble by setting the webhook port correctly

### DISCUSSION THREAD

**Discussion by peppelin** [8gears/n8n-helm-chart#191] [Q&A]
Hi,

I'm using 4 raspberry pi k3s nodes and I've been able to install n8n with helm.
I'm struggling to set the webhook correctly as it shows the 5678 port every time (and it's listening to the 80 and 443).

Here's my config if anyone spots what I'm doing wrong:

```main:
  config:
    n8n:
      timezone: "Europe/Paris"
      webhook_url: "https://n8n.mydomain.com"
      host: "n8n.mydomiain.com"               
      # port: 443                          
      protocol: "https"                      

  service:
    type: ClusterIP
    port: 80      
    targetPort: 5678  
    

  ingress:
    enabled: false
```
    
 The webhook I get in n8n is as follows:
 `ttps://n8n.mydomain.com:5678/webhook/xxxxx`

Thanks in advance.

**Comment by peppelin** [comment]
Ok, found it. 

After further investigation, I found the configmaps with my actual config were not what I was expecting.

Troubleshooting:
I got the pod information and checked where the env vars where being loaded from:
```
kubectl get pod -n n8n n8n-6c686fc468-hs5dr -o yaml
apiVersion: v1
kind: Pod
...
spec:
  containers:
  - envFrom:
    - configMapRef:
        name: app-config-n8n
...
```
When checking the configmas, I saw the pattern that was messing with the port:
```
k get configmaps -n n8n app-config-n8n -o yaml
apiVersion: v1
data:
  N8N_HOST: n8n.mydomain.com
  N8N_PROTOCOL: https
  N8N_TIMEZONE: Europe/Paris
  N8N_WEBHOOK_URL_VALUE: https://n8n.mydomain.com/
```
Inside the container, the envvar was named  N8N_WEBHOOK_URL_VALUE and it was expecting WEBHOOK_URL

```
kubectl exec -it -n n8n n8n-85cf7bb75b-cqx8w -- printenv
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=n8n-85cf7bb75b-cqx8w
NODE_VERSION=20.18.2
YARN_VERSION=1.22.22
NODE_ICU_DATA=/usr/local/lib/node_modules/full-icu
N8N_VERSION=1.76.1
NODE_ENV=production
N8N_RELEASE_TYPE=stable
SHELL=/bin/sh
N8N_HOST=n8n.peppelin.com
N8N_PROTOCOL=https
N8N_TIMEZONE=Europe/Paris
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1
N8N_PORT_80_TCP_ADDR=10.43.79.232
KUBERNETES_SERVICE_PORT=443
N8N_SERVICE_PORT_HTTP=80
N8N_PORT_80_TCP=tcp://10.43.79.232:80
KUBERNETES_PORT=tcp://10.43.0.1:443
KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
N8N_SERVICE_HOST=10.43.79.232
N8N_SERVICE_PORT=80
N8N_PORT=tcp://10.43.79.232:80
N8N_PORT_80_TCP_PROTO=tcp
N8N_PORT_80_TCP_PORT=80
N8N_WEBHOOK_URL_VALUE: https://n8n.mydomain.com
KUBERNETES_SERVICE_HOST=10.43.0.1
TERM=xterm
HOME=/home/node
```
**SOLUTION**
Updated the config as below, and launched again:

```
main:
  config:
    WEBHOOK_URL: "https://n8n.mydomain.com/" 
    n8n:
      timezone: "Europe/Paris"
      host: "n8n.mydomain.com" 
      protocol: "https"
```
