### ISSUE TITLE
Different liveness probe for workers vs control pod

### ISSUE THREAD

**Issue by knuurr** [8gears/n8n-helm-chart#120]
We are testing  a very specific liveness probe for control n8n node, because due to our workload it happens that control pod hangs, and any workflows won't run until this pod is manually restarted by someone from our crew. unfortunately `/healthz` endpoint doesn't catch this very specific scenario in our situation.

```yml
# Test liveness probe workaround for n8n hanging
livenessProbe:
  exec:
    command:
    - /bin/sh
    - -c
    - | 
      wget -q --post-data='{ "type": "test" }' --spider http://n8n.namespace.svc.cluster.local/webhook/event
  initialDelaySeconds: 30  # Wait 30 seconds before starting the first probe
  periodSeconds: 60        # Run the liveness probe every full minute (60 seconds)
  timeoutSeconds: 5        # Fail if the command doesn't return within 5 seconds
  failureThreshold: 4      # After 3 failures, the pod will be restarted
  successThreshold: 1      # One success is enough to declare the pod healthy
```

However setting this in `values.yaml` sets it up also for worker nodes, which we don't need now.

Is there any possibility to set different liveness probes for control only, and different (so default) for workers, using this helm chart template?
