### ISSUE TITLE
[Error] EACCES: permission denied, mkdir '/home/node/.cache' error when deploying n8n Helm chart on EKS cluster

### ISSUE THREAD

**Issue by Vinaum8** [8gears/n8n-helm-chart#123]
I encountered an issue while installing the n8n Helm chart on an EKS cluster (version v1.30.4-eks-a737599).

Helm chart Version:
**component**: n8n
**project**: automation
**repoURL**: 8gears.container-registry.com/library
**version**: 0.25.2
**namespace**: automation

When deploying the chart, I faced the following error: EACCES: permission denied, mkdir '/home/node/.cache'. After researching, I found this [discussion on the n8n community forum](https://community.n8n.io/t/eacces-permission-denied-mkdir-cache-when-upgrading-to-0-196-0/22842), which suggests manually adding a volume for the cache directory.

To resolve this issue, I had to manually edit the deployment to add the following configuration:

```
volumeMounts:
      - mountPath: /home/node/.cache
        name: n8n-cache
volumes:
  - name: n8n-cache
    emptyDir: {}
```

Can this be incorporated into the Helm chart’s values.yaml so that the /home/node/.cache directory is automatically created with the correct permissions? Alternatively, could there be an option to configure this in values.yaml to avoid manual edits?
