### ISSUE TITLE
Create an option for extraEnvFrom

### ISSUE THREAD

**Issue by jschmidtcordeiro** [8gears/n8n-helm-chart#139]
# What should be done?

Should be added a new option under `.Values.main` to support extraEnvFrom. So the new option would be `.Values.main.extraEnvFrom`.

# Why?

This way we can pass extra secrets that already exists in Kubernetes namespace into the n8n application.

# How?

1. Add a new option in the values

![Image](https://github.com/user-attachments/assets/ce01d53a-8bab-46c7-bdf8-7ab2ed9e8ebe)

2. Add the reference where the new option will be set, in `deployment.yaml` under `spec.containers.envFrom`

![Image](https://github.com/user-attachments/assets/75f64a32-be40-4c59-82ea-541b1e0b8e5f)

**Comment by Vad1mo** [comment]
It is already possible to reference env in external configmap and secret with `env`.

The reason I don't think this feature makes sense here is the following:
1.  When you reference outside configmap/secret the keys aren't always in the format needed, so you have to remap.
 
With env. you can import individual ENV pairs. see example:

```yaml
  extraEnv:
    DB_POSTGRESDB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: db-app
          key: password
````

I am open to changing my mind if there is a strong case for that.
