### ISSUE TITLE
Wrong valkey (redis) sub-chart config key

### ISSUE THREAD

**Issue by hinorashi** [8gears/n8n-helm-chart#145]
Let's say we wanna overwrite valkey config like this:
```yaml
# Bitnami Valkey configuration
# https://artifacthub.io/packages/helm/bitnami/valkey
redis:
  enabled: true
  architecture: standalone

  primary:
    persistence:
      enabled: true
      size: 2Gi
```

However, we end up with the default "replication" architecture and all other default values for valkey (redis).

I took a look at the `Chart.yaml`:
```yaml
dependencies:
- condition: redis.enabled
  name: valkey
```

So it should be configured like this:
```yaml
redis:
  enabled: true

# the sub-chart will read this key
valkey:
  architecture: standalone

  primary:
    persistence:
      enabled: true
      size: 2Gi
```

Or we simply just change the name to valkey (over redis) in `Chart.yaml` to avoid ambiguity:
```yaml
dependencies:
- condition: valkey.enabled
  name: valkey
```

And update `values.yaml` accordingly:
```yaml
# Bitnami Valkey configuration
# https://artifacthub.io/packages/helm/bitnami/valkey
valkey:
  enabled: true
  architecture: standalone

  primary:
    persistence:
      enabled: true
      size: 2Gi
```

Because we all know that **valkey** and **redis** are now 2 different brands 😆
