### ISSUE TITLE
Using extraEnv for database login causes "password authentication failed for user"

### ISSUE THREAD

**Issue by Fank** [8gears/n8n-helm-chart#146]
Using chart version 1.0.1 .

![Image](https://github.com/user-attachments/assets/058be88a-d054-49fd-a3d1-e28df4ca32d5)

When using `config` it works fine like this:
```
#small deployment with nodeport for local testing or small deployments
main:
  config:
    n8n:
      hide_usage_page: true
    db:
      type: postgresdb
      postgresdb:
        database: n8n-stage
        host: n8n-pg-cluster-rw
        user: n8n-stage
        password: "asdasdasd"
  secret:
    n8n:
      encryption_key: "asdasdasds"
#  extraEnv:
#    DB_POSTGRESDB_USER:
#      valueFrom:
#        secretKeyRef:
#          name: pg-user-n8n-stage
#          key: username
#    DB_POSTGRESDB_PASSWORD:
#      valueFrom:
#        secretKeyRef:
#          name: pg-user-n8n-stage
#          key: password
  deploymentStrategy:
    type: RollingUpdate
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi
  service:
    annotations:
      cloud.google.com/neg: '{"exposed_ports": {"8080":{}}}'
    type: NodePort

```

The secret is using the http basic secret from cloudnative-pq: https://cloudnative-pg.io/documentation/1.20/declarative_role_management/#password-management

**Comment by Fank** [comment]
```
    QUEUE_BULL_REDIS_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: n8n-redis-redis-cluster
          key: redis-password
```
The secret created by https://github.com/bitnami/charts/tree/main/bitnami/redis-cluster worked without issues.
