### ISSUE TITLE
Worker restarting due to readiness probe - 1.0.4

### ISSUE THREAD

**Issue by kchebani** [8gears/n8n-helm-chart#159]
Hi,

I upgraded from Chart 1.0.1 to 1.0.4 and used the new worker configuration. But My workers were always restarting.

The workers needs this env variable to be set to listen to port 5678 or they will restart due to the readiness probe :

`QUEUE_HEALTH_CHECK_ACTIVE`

I added to my values file :

```
worker:
  enabled: true
  extraEnv:
    QUEUE_HEALTH_CHECK_ACTIVE: 
      value: "true"
```

Here is the n8n documentation link : https://docs.n8n.io/hosting/scaling/queue-mode/#worker-server

Hope it helps you.
