### ISSUE TITLE
`n8n-webhook` deployment in CrashLoopBackOff without any log

### ISSUE THREAD

**Issue by noghartt** [8gears/n8n-helm-chart#172]
Hey, i'm trying to setup the chart exposing the webhook accordingly the `values.yaml`, but basically, my `n8n-webhook` deployment still in a CrashLoopBackOff, but I don't have any insight in how to debug it, even because there's no log (with `N8N_LOG_LEVEL` env being `info`).

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/050dfda5-1ba5-4671-bea8-451bf8ae211c" />

Also, the output of my `describe` didn't add anything useful:

```
│ Events:                                                                                                                                                                                  │
│   Type     Reason     Age                  From               Message                                                                                                                    │
│   ----     ------     ----                 ----               -------                                                                                                                    │
│   Normal   Scheduled  40m                  default-scheduler  Successfully assigned n8n/n8n-webhook-5bc6fd8477-lnv5z to k8s-worker-1                                                     │
│   Normal   Pulled     38m (x5 over 40m)    kubelet            Container image "n8nio/n8n:1.83.0" already present on machine                                                              │
│   Normal   Created    38m (x5 over 40m)    kubelet            Created container: n8n-webhook                                                                                             │
│   Normal   Started    38m (x5 over 40m)    kubelet            Started container n8n-webhook                                                                                              │
│   Warning  BackOff    46s (x190 over 40m)  kubelet            Back-off restarting failed container n8n-webhook in pod n8n-webhook-5bc6fd8477-lnv5z_n8n(9ce6225f-f703-457a-8915-914936e47 │
│ 392)
```

My current values are:
```yaml
_shared_config:
  host: &host 10.43.244.41

n8n:
  main:
    extraEnv: &env
      - name: N8N_RUNNERS_ENABLED
        value: "true"
      - name: N8N_PORT
        value: "5678"
      - name: N8N_PROTOCOL
        value: "http"
      - name: N8N_LOG_LEVEL
        value: "info"

  webhook:
    enabled: true

    extraEnv: *env

    livenessProbe:
      httpGet:
        host: *host
        path: /healthz
        port: 5678
      initialDelaySeconds: 120
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 10

    readinessProbe:
      httpGet:
        host: *host
        path: /healhtz
        port: 5678
      initialDelaySeconds: 120
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 10

  valkey:
    enabled: true
    architecture: standalone

    primary:
      persistence:
        enabled: false
        existingClaim: ""
        size: 2Gi
```

I added the `host` being the `ClusterIP` assigned to my `n8n` main deployment. Any idea why exactly it still being on a CrashLoopBackOff? Or at least how could I better debug it?
