### ISSUE TITLE
HPA for worker and webhook

### ISSUE THREAD

**Issue by Rez0k** [8gears/n8n-helm-chart#179]
Hi guys.

I an wondering why there is no hpa for the worker and the webhhok?

is it possible to add this manifests?

**Comment by Rez0k** [comment]
any updaet?

**Comment by JHTosas** [comment]
I guess you mean https://github.com/8gears/n8n-helm-chart/pull/186 ? I'm also waiting on that... :(

**Comment by hinorashi** [comment]
don't wait, create one for yourself:
```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: n8n-worker
  namespace: n8n
spec:
  scaleTargetRef:
    kind: Deployment
    name: n8n-worker
    apiVersion: apps/v1
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
```
