### ISSUE TITLE
Webhook processes rely on Valkey. Please set a Redis/Valkey host

### ISSUE THREAD

**Issue by jaredjadu** [8gears/n8n-helm-chart#182]
Chart Version 1.0.6
EKS
Deployment via ArgoCD

I am trying to enable the webhook option but receiving the following error on deployment

```
Webhook processes rely on Valkey. Please set a Redis/Valkey host 
```

I have tried setting the valkey / redis host in the webhook section and tried it in the main section

```
webhook:
  enabled: true
  extraEnv: 
    WEBHOOK_URL:
      value: "https://dev-n8nhook.snip.net"
    QUEUE_BULL_REDIS_HOST:
      value: "n8n-scaled-valkey-primary"
```

I can't see any mention in the values.yaml file about setting this anywhere else?

my valkey section
```
valkey:
  enabled: true
  auth:
    enabled: false
  architecture: replication
  primary:
    persistence:
      enabled: true
      type: dynamic
      accessModes:
        - ReadWriteOnce
      size: 1Gi
```
