### ISSUE TITLE
container-registry auth?

### ISSUE THREAD

**Issue by dylannevans** [8gears/n8n-helm-chart#183]
Hi folks. Seems like I'm missing something dumb, but trying to install per directions gives me an unauthorized when pointing at the oci. Are there screds somewhere I missed?  

```
$helm install my-n8n oci://8gears.container-registry.com/library/n8n --version 1.0.6 --debug
install.go:224: 2025-05-11 13:21:49.625455969 -0500 CDT m=+0.086369658 [debug] Original chart version: "1.0.6"
DEBU[0000] resolving                                     host=8gears.container-registry.com
DEBU[0000] do request                                    host=8gears.container-registry.com request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=Helm/3.16.4 request.method=HEAD url="https://8gears.container-registry.com/v2/library/n8n/manifests/1.0.6"
DEBU[0000] fetch response received                       host=8gears.container-registry.com response.header.content-length=152 response.header.content-type="application/json; charset=utf-8" response.header.date="Sun, 11 May 2025 18:21:50 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.set-cookie="sid=aed230bf0ad0bfe3ec50609accf5b8d0; Path=/; HttpOnly" response.header.strict-transport-security="max-age=31536000; includeSubDomains" response.header.www-authenticate="Bearer realm=\"https://8gears.container-registry.com/service/token\",service=\"harbor-registry\",scope=\"repository:library/n8n:pull\"" response.header.x-request-id=df28692fd82c71b2f5db0c6d269b2505 response.status="401 Unauthorized" url="https://8gears.container-registry.com/v2/library/n8n/manifests/1.0.6"
DEBU[0000] Unauthorized                                  header="Bearer realm=\"https://8gears.container-registry.com/service/token\",service=\"harbor-registry\",scope=\"repository:library/n8n:pull\"" host=8gears.container-registry.com
INFO[0000] trying next host                              error="error getting credentials - err: exec: \"docker-credential-desktop.exe\": executable file not found in $PATH, out: ``" host=8gears.container-registry.com
Error: INSTALLATION FAILED: error getting credentials - err: exec: "docker-credential-desktop.exe": executable file not found in $PATH, out: ``
helm.go:86: 2025-05-11 13:21:50.105774226 -0500 CDT m=+0.566687915 [debug] error getting credentials - err: exec: "docker-credential-desktop.exe": executable file not found in $PATH, out: ``
```

relevant version: 
```
$ helm version
version.BuildInfo{Version:"v3.16.4", GitCommit:"7877b45b63f95635153b29a42c0c2f4273ec45ca", GitTreeState:"clean", GoVersion:"go1.22.7"}

```
Further context: My goal for this helmchart is in a flux gitops recipe, something like: 

```
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: n8n
  namespace: flux-system
spec:
  url: oci://8gears.container-registry.com/library/n8n
  type: oci
  interval: 24h
---
kind: HelmRelease
metadata:
  name: n8n
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: appstack
  releaseName: n8n
  chart:
    spec:
      chart: n8n
      sourceRef:
        kind: HelmRepository
        name: n8n
  values:
    main:
      config:
        <conf>
```

**Comment by dylannevans** [comment]
I ended up writing my own.

**Comment by dylannevans** [comment]
> The repository is public; no authentication needed to pull the chart...

If you say so, dude. But when the repo consistently says, "rejected, auth creds required," it's not very persuasive :\.

Honestly, It's fine to gate access. It's a pretty reasonable thing these days. At the minimum, it means you don't have to worry about goofs on the internet complaining about problems with it on your repo ;).

**Comment by Vad1mo** [comment]
For reference, if anyone here is having a problem pulling the chart. 

**No authentication is required to pull the chart; if you can't pull it, it is on your side.** 

Here you can browse all the public n8n charts. Only the UI and private projects require auth, but you don't need that to pull the image. 


https://8gears.container-registry.com/harbor/projects/1/repositories/n8n/artifacts-tab?publicAndNotLogged=yes

**Comment by chedim** [comment]
@dylannevans dude, there are 3 issues with your flux definitions:
1. Use OCIRepository instead of HelmRepository
2. specify repo tag (this is why you are getting a 401)
3. your helmrelease needs to use new `spec.chartRef` fields for OCI
here, this works:
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: 8gears-n8n
  namespace: default
spec:
  interval: 5m0s
  url: oci://8gears.container-registry.com/library/n8n
  ref:
    tag: 1.1.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: default
spec:
  interval: 10m
  releaseName: n8n
  chartRef:
    kind: OCIRepository
    name: 8gears-n8n
  values:
      ....
```
