### ISSUE TITLE
UPGRADE FAILED Please set a Redis/Valkey host when webhook.enabled=true

### ISSUE THREAD

**Issue by flowramps** [8gears/n8n-helm-chart#184]
At the moment, I'm trying to use the latest version 1.0.6, but I'm having difficulty understanding how to enable integration between the webhook and Valkey. When analyzing the documentation, I didn't find anything that made this integration clear.

```
╰─ helm upgrade n8n oci://8gears.container-registry.com/library/n8n --version 1.0.6 -f values-1-0-6-hml.yaml
─╯
Pulled: 8gears.container-registry.com/library/n8n:1.0.6
Digest: sha256:71f0e96d9ff823c4e52292a1e6e87b93a9167e95a2daa1d9066db96dab1771a9
Error: UPGRADE FAILED: execution error at (n8n/templates/deployment.webhook.yaml:3:4): Webhook processes rely on Valkey. Please set a Redis/Valkey host when webhook.enabled=true
```
In the old version 0.25.2, before changing the values, I already had the entire stack configured with webhook, worker and Redis. Any ideas or examples of how to enable in version 1.0.6?

**Comment by Vad1mo** [comment]
There was a no example specific to your case. But the semantics didn't change. What you need to do is find the new keys to you existing values. 
Valkey did only had a version bump.

**Comment by flowramps** [comment]
Using the following chart https://artifacthub.io/packages/helm/open-8gears/n8n/1.0.6?modal=values


Values ​​that I am trying to use below, what could I adjust for communication between components?

Redis - internal
Postgresdb - external
Work - enabled
webhook enabled with smtp for sending

In the old version, the entraEnv is like this and in the new model I am not able to fit these values ​​either,

@Vad1mo Would you have a ready-made model of how I can adjust this field for this chart version? 

```
extraEnv:
    N8N_METRICS: "true" # Metrics
    QUEUE_HEALTH_CHECK_ACTIVE: "true" # Metrics
    N8N_METRICS_INCLUDE_WORKFLOW_ID_LABEL: "true" # Metrics
    N8N_METRICS_INCLUDE_API_STATUS_CODE_LABEL: "true" # Metrics
    N8N_METRICS_INCLUDE_API_ENDPOINTS: "true" # Metrics
    N8N_METRICS_INCLUDE_API_METHOD_LABEL: "true" # Metrics
    N8N_METRICS_INCLUDE_QUEUE_METRICS: "true" # Metrics
    N8N_METRICS_INCLUDE_API_PATH_LABEL: "true" # Metrics
    N8N_METRICS_INCLUDE_CREDENTIAL_TYPE_LABEL: "true" # Metrics
    N8N_METRICS_INCLUDE_NODE_TYPE_LABEL: "true" # Metrics
    N8N_METRICS_INCLUDE_MESSAGE_EVENT_BUS_METRICS: "true" # Metrics
    N8N_METRICS_INCLUDE_DEFAULT_METRICS: "true" # Metrics
    N8N_EMAIL_MODE: "smtp"
    N8N_SMTP_HOST: "smtp-XXXXXXXX"
    N8N_SMTP_PORT: 25
    N8N_SMTP_SENDER: "XXXXXXXXXXXXXXXXXX"
    N8N_SMTP_SSL: false
    QUEUE_BULL_REDIS_TLS: "true"
    NODE_TLS_REJECT_UNAUTHORIZED: "0"
    GENERIC_TIMEZONE: "XXXXXXXXXXXXXXX"
    WEBHOOK_URL: "https://domain.com.br"
    DB_POSTGRESDB_SSL_ENABLED: "true"
```
```
# Ingress
#
ingress:
  enabled: true
  annotations: {}
  # define a custom ingress class Name, like "traefik" or "nginx"
  className: "nginx"
  hosts:
    - host: domain.com.br
      paths:
        - /
  tls:
    - hosts:
        - domain.com.br
      secretName: ssl

main:

  config:
    n8n:
      logs:
        level: debug
      db:
        type: postgresdb
        postgresdb:
          database: XXXXXXXXXXXXXX  # PostgresDB Database - default: n8n
          host: XXXXXXXXXXXXXXXXXXX.sa-east-1.rds.amazonaws.com  # PostgresDB Host - default: localhost
          port: 5432 # PostgresDB Port - default: 5432
          user: XXXXXXXXXXXXXXXXXXX # PostgresDB User - default: root
          schema: n8n # PostgresDB Schema - default: public
  secret:
    n8n:

      encryption_key: "XXXXXXXXXXXXXXXXXXX"

      db:
        postgresdb:
          password: 'XXXXXXXXXXXXXXX'

worker:
  enabled: false
  replicaCount: 1
  extraEnv:
    - name: N8N_ENCRYPTION_KEY
      value: "XXXXXXXXXXXXXXX"
    - name: N8N_REDIS_HOST
      value: n8n-valkey-headless
    - name: N8N_REDIS_PORT
      value: "6379"
    - name: N8N_REDIS_PASSWORD
      value: "XXXXXXXXXXXXXXX"




webhook:
  enabled: true

# Bitnami Valkey configuration
# https://artifacthub.io/packages/helm/bitnami/valkey
valkey:
  enabled: true
  auth:
    enabled: true
    password: XXXXXXXXXXXXXXXX
```

**Comment by flowramps** [comment]
Okay, I'll give the following example below. In version 0.25.2, my values.yaml is working as follows.

Below, I show how I am unable to map the values ​​to external Redis in version 1.0.6. I will separate it into blocks; If you can analyze and help me identify where I may be going wrong, I would appreciate it.

values-0-25-2.yaml
```
# Default helm values for n8n.
# Default values within the n8n application can be found under https://github.com/n8n-io/n8n/blob/master/packages/cli/src/config/index.ts
n8n:
  # if not specified n8n on first launch creates a random encryption key for encrypting saved credentials and saves it in the ~/.n8n folder
  encryption_key: XXXXXXXXXXXXXXX
defaults:

config:
  executions:
    # prune executions by default
    pruneData: "true"
    # Per default, we store 1 year of history
    pruneDataMaxAge: 3760

secret:

   logs:
      level: debug
   database:
    type: postgresdb            # Type of database to use - Other possible types ['sqlite', 'mariadb', 'mysqldb', 'postgresdb'] - default: sqlite
    #tablePrefix:      # Prefix for table names - default: ''
    postgresdb:
      database: XXXXXXXXXXXXXXX  # PostgresDB Database - default: n8n
      host: XXXXXXXXXXXXXXX  # PostgresDB Host - default: localhost
      password: XXXXXXXXXXXXXXX # PostgresDB Password - default: ''
      port: 5432 # PostgresDB Port - default: 5432
      user: XXXXXXXXXXXXXXX # PostgresDB User - default: root
      schema: n8n # PostgresDB Schema - default: public

extraEnv:
    N8N_METRICS: "true" # Metrics
    QUEUE_HEALTH_CHECK_ACTIVE: "true" # Metrics
    N8N_METRICS_INCLUDE_WORKFLOW_ID_LABEL: "true" # Metrics
    N8N_METRICS_INCLUDE_API_STATUS_CODE_LABEL: "true" # Metrics
    N8N_METRICS_INCLUDE_API_ENDPOINTS: "true" # Metrics
    N8N_METRICS_INCLUDE_API_METHOD_LABEL: "true" # Metrics
    N8N_METRICS_INCLUDE_QUEUE_METRICS: "true" # Metrics
    N8N_METRICS_INCLUDE_API_PATH_LABEL: "true" # Metrics
    N8N_METRICS_INCLUDE_CREDENTIAL_TYPE_LABEL: "true" # Metrics
    N8N_METRICS_INCLUDE_NODE_TYPE_LABEL: "true" # Metrics
    N8N_METRICS_INCLUDE_MESSAGE_EVENT_BUS_METRICS: "true" # Metrics
    N8N_METRICS_INCLUDE_DEFAULT_METRICS: "true" # Metrics
    N8N_EMAIL_MODE: "smtp"
    N8N_SMTP_HOST: "XXXXXXXXXXXXXXX"
    N8N_SMTP_PORT: 25
    N8N_SMTP_SENDER: "XXXXXXXXXXXXXXX"
    N8N_SMTP_SSL: false
    NODE_TLS_REJECT_UNAUTHORIZED: "0"
    GENERIC_TIMEZONE: "XXXXXXXXXXXXXXX"
    WEBHOOK_URL: "https://domain.com.br"
    DB_POSTGRESDB_SSL_ENABLED: "true"
    QUEUE_BULL_REDIS_HOST: redis-master.n8n.svc.cluster.local
    QUEUE_BULL_REDIS_TLS: "false"

extraEnvSecrets: {}

persistence:
  enabled: false
  type: emptyDir

  accessModes:
    - ReadWriteOnce
  size: 1Gi
replicaCount: 1

deploymentStrategy:
  type: "Recreate"

image:
  repository: n8nio/n8n
  pullPolicy: IfNotPresent

  tag: ""

imagePullSecrets:
- name: docker-hub

nameOverride: ""

fullnameOverride: ""

serviceAccount:

  create: true

  annotations: {}

  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext: {}

lifecycle:
  {}

command: []


livenessProbe: null

readinessProbe: null

initContainers: []

service:
  type: ClusterIP
  port: 80
  annotations: {}

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

  className: "nginx"
  hosts:
  - host: domain.com.br
    paths:
      - /
  tls:
    - hosts: 
        - domain.com.br
      secretName: ssl

workerResources:
  {}

webhookResources:
  {}

resources:

   requests:
     cpu: "500m"
     memory: "2000Mi"
   limits:
     cpu: "1000m"
     memory: "4Gi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

scaling: #Segundo módulo para separação de recursos ao invés de trabalhar como monolito mode queue
  enabled: true

  worker:
    count: 4 # Isso significa que serão iniciados 4 instâncias de workers do n8n. Cada worker funcionará de forma independente, processando suas tarefas.
    concurrency: 2 # Cada worker poderá processar até 2 tarefas simultaneamente.

  webhook:
    enabled: true
    count: 1

  redis:
    host: redis-master.n8n.svc.cluster.local



## Bitnami Redis configuration
## https://github.com/bitnami/charts/tree/master/bitnami/redis
redis:
  enabled: false
  auth:
    enabled: true
    username: XXXXXXXXXXXXXXX
    password: XXXXXXXXXXXXXXX

  architecture: standalone

  master:
    persistence:
      enabled: false
      existingClaim: ""
      size: 2Gi
```




In version 1.0.6 I am not able to map the webhook with external redis, what would be missing or wrong @Vad1mo ?

╰─ helm upgrade n8n oci://8gears.container-registry.com/library/n8n --version 1.0.6 -f values-1-0-6-hml-stack.yaml
─╯
Pulled: 8gears.container-registry.com/library/n8n:1.0.6
Digest: sha256:71f0e9xxxxxxxxxxxxxxxxxxxxxxxxxxx
Error: UPGRADE FAILED: execution error at (n8n/templates/deployment.webhook.yaml:3:4): Webhook processes rely on Valkey. Please set a Redis/Valkey host when webhook.enabled=true

the only thing missing is the redis integration with the webhook!

values-1-0-6.yaml

```
ingress:
  enabled: true
  annotations: {}
  # define a custom ingress class Name, like "traefik" or "nginx"
  className: "nginx"
  hosts:
    - host: domain.com.br
      paths:
        - /
  tls:
    - hosts:
        - domain.com.br
      secretName: ssl
main:
  # See https://docs.n8n.io/hosting/configuration/environment-variables/ for all values.
  config:
      queue:
        mode: redis
        redis:
          host: redis-master.n8n.svc.cluster.local
          port: 6379
          db: 0

      db:
        type: postgresdb
        postgresdb:
          database: XXXXXXXXXXXXXX  # PostgresDB Database - default: n8n
          host: XXXXXXXXXXXXXX  # PostgresDB Host - default: localhost
          port: 5432 # PostgresDB Port - default: 5432
          user: XXXXXXXXXXXXXX # PostgresDB User - default: root
          schema: n8n # PostgresDB Schema - default: public

  secret:
    logs:
       level: debug
    n8n:

      encryption_key: XXXXXXXXXXXXXX

    db:
      postgresdb:
        password: 'XXXXXXXXXXXXXX'

  extraEnv:
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS:
      value: "true"
    N8N_RUNNERS_ENABLED:
      value: "true"
    NODE_TLS_REJECT_UNAUTHORIZED:
      value: "0"
    GENERIC_TIMEZONE:
      value: "XXXXXXXXXXXXXXX"
    TZ:
      value: "XXXXXXXXXXXXXXX"
    N8N_EMAIL_MODE:
      value: "smtp"
    N8N_SMTP_HOST:
      value: "XXXXXXXXXXXXXXX"
    N8N_SMTP_PORT:
      value: "25"
    N8N_SMTP_SENDER:
      value: "XXXXXXXXXXXXXXX"
    N8N_SMTP_SSL:
      value: "false"
    WEBHOOK_URL:
      value: "https://domain.com.br"
    DB_POSTGRESDB_SSL_ENABLED:
      value: "true"
    QUEUE_BULL_REDIS_TLS:
      value: "false"
    N8N_PORT:
      value: "5678"
    N8N_EXECUTIONS_MODE:
      value: "queue"
    N8N_QUEUE_MODE_REDIS_HOST:
      value: "redis-master.n8n.svc.cluster.local"
    N8N_QUEUE_MODE_REDIS_PORT:
      value: "6379"
    QUEUE_BULL_REDIS_HOST:
      value: "redis-master.n8n.svc.cluster.local"
    QUEUE_BULL_REDIS_PORT:
      value: "6379"
    QUEUE_BULL_REDIS_DB:
      value: "0"

worker:
  enabled: true

webhook:
  enabled: true

  extraEnv:
    QUEUE_BULL_REDIS_HOST:
      value: "redis-master.n8n.svc.cluster.local"
    QUEUE_BULL_REDIS_TLS:
      value: "false"

valkey:
  enabled: false
  auth:
    enabled: false
  architecture: standalone

```

**Comment by simonefrancia** [comment]
I have the same problem with webhook

**Comment by simonefrancia** [comment]
I have fixed adding last 4 lines of this snippet.

```
main:
  config:
    executions: null
    executions_mode: queue
    db:
      type: postgresdb
      tablePrefix: 'prefix_'
      postgresdb:
        database: db
        host: host
        port: port
        user: user
    queue:
      health:
        check:
          active: true
      bull:
        redis:
          host: redis-host
          port: redis-port
```
