### ISSUE TITLE
multi attach error

### ISSUE THREAD

**Issue by dusmeyenlabut** [8gears/n8n-helm-chart#189]
Hello team,
I would like to run n8n with webhook and worker enabled property. This is my values yaml for test the chart on my azure aks kubernetes cluster.
```yaml
#Prod like set up with CloudNativePG and nginx-ingress

# Define hostname anchor at the top of the file
_shared_config:
  hostname: &hostname test-abc.com
  url: &url https://test-abc.com
#image:
#  repository: 8gears.container-registry.com/ops/n8n
#  tag: 1.81.4
#  pullPolicy: Always
#imagePullSecrets:
#  - name: 8gears-registry-n8n
main:
  config:
    n8n:
      editor_base_url: *url
    executions_mode: queue
    endpoints:
      disableProductionWebhooksOnMainProcess: true
    db:
      type: "postgresdb"
      postgresdb:
        host: "my-postgres"
        user: "postgres"
        database: "postgres"
        port: 6432
        schema: n8n
        ssl:
          enabled: true
    # webhook related settings
    webhook_url: "https://webhook-test-abc.com"
    queue:
      health:
        check:
          active: true
      bull:
        redis:
          host: redis-master.n8n
          port: 6379
          password: mypass
  secret:
    n8n:
      encryption_key: "<your-secure-encryption-key>"
    db:
      postgresdb:
        password: "mysuperpass"
  extraEnv: &extraEnv
    DB_POSTGRESDB_PASSWORD:
      value: "mysuperpass"
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi
  persistence:
    enabled: true
    type: dynamic
worker:
  enabled: true
  extraEnv: *extraEnv # using YAML magic (anchors) to reference main extraEnv
  replicaCount: 10
  persistence:
    enabled: false
    type: emptyDir
webhook:
  enabled: true
  extraEnv:
   WEBHOOK_URL:
     value: "https://webhook-test-abc.com"
   DB_POSTGRESDB_PASSWORD:
    value: "mysuperpass"
  replicaCount: 10
  persistence:
    enabled: false
    type: emptyDir
valkey:
  enabled: false
ingress:
  enabled: false
```

I am getting multi attach error for webhook and work pods when they scheduled on a different k8s node. How can it be possible to handle them with different nodes and several replicas? Or am I missing something?

I also tried with affinity rule to schedule all replicas on same node and everyting works fine. But as you know I am losing k8s ability of rescheduling on a different node when usage is too high.
