### ISSUE TITLE
extraEnv no longer work with valueFrom

### ISSUE THREAD

**Issue by fcharlaix-opendsi** [8gears/n8n-helm-chart#200]
When updating the chart to 1.0.9, n8n can't start due to all the `extraEnv` set as `valueFrom` no longer working.

My values : 
```yaml
  extraEnv:
    N8N_ENCRYPTION_KEY:
      valueFrom:
        secretKeyRef:
          name: n8n-env
          key: encryption
    DB_POSTGRESDB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: postgres
          key: password
    N8N_SMTP_PASS:
      valueFrom:
        secretKeyRef:
          name: n8n-env
          key: smtp
```

The result :
```
    Environment Variables from:
      n8n-app-config  ConfigMap  Optional: false
    Environment:
      DB_POSTGRESDB_PASSWORD:  map[valueFrom:map[secretKeyRef:map[key:password name:postgres]]]
      N8N_ENCRYPTION_KEY:      map[valueFrom:map[secretKeyRef:map[key:encryption name:n8n-env]]]
      N8N_SMTP_PASS:           map[valueFrom:map[secretKeyRef:map[key:smtp name:n8n-env]]]
```

This impacts, in my case, the encryption key, the database password and the SMTP password, my chart values are committed, so I don't want any plain password in the config.

This seems to be caused by the removal of the `toYaml` in `charts/n8n/templates/deployment.yaml` on the commit [d9b9a70](https://github.com/8gears/n8n-helm-chart/commit/d9b9a70a18745574daf9855520ab9973bc87477a) : 

![Image](https://github.com/user-attachments/assets/112f6a7d-0cfb-4508-a44d-a1613004d232)

This breaks the example comment :
https://github.com/8gears/n8n-helm-chart/blob/d9b9a70a18745574daf9855520ab9973bc87477a/charts/n8n/values.yaml#L76-L82

I didn't submit a PR since this was removed to fix another problem that I didn't encounter
