### ISSUE TITLE
Service annotations not being written into n8n/templates/service.yaml

### ISSUE THREAD

**Issue by kaifresh** [8gears/n8n-helm-chart#23]
I have defined some values in a `values.yaml` file for the Service like so (I am deploying on GKE and want to associate a BackendConfig with the Service)

```yaml

service:
  type: ClusterIP
  port: 80
  annotations: # THIS ISNT BEING WRITTEN INTO THE TEMPLATED KUBERNETES CONFIG....
    # Backend Config created along side the ingress
    cloud.google.com/backend-config: '{"ports":{"http":"whitelist-cloudflare-only-via-security-policies", "https":"whitelist-cloudflare-only-via-security-policies"}}'
```

However, when I use the `--dry-run` and `--debug` flags, what I see is:
```yaml
 ---
 # Source: n8n/templates/service.yaml
apiVersion: v1
 kind: Service
 metadata:
   name: n8n
   labels:
     helm.sh/chart: n8n-0.5.0
     app.kubernetes.io/name: n8n
     app.kubernetes.io/instance: n8n
     app.kubernetes.io/version: "0.111.0"
     app.kubernetes.io/managed-by: Helm
 spec:
   type: ClusterIP
   ports:
     - port: 80
       targetPort: http
       protocol: TCP
       name: http
   selector:
     app.kubernetes.io/name: n8n
     app.kubernetes.io/instance: n8n

```

Which suggests that the [annotations part of the config referenced here](https://github.com/8gears/n8n-helm-chart/blob/25a4df5f4d4dc279134872fec6d2c971744374ce/templates/service.yaml#L7) is not being written into the template. 

# The question
Is my syntax wrong? The readme suggests `annotations` is just an object. Or is there something that needs to be changed in the template itself?
