### ISSUE TITLE
Error installing helm chart: deployment.yaml wrong type for value

### ISSUE THREAD

**Issue by davinerd** [8gears/n8n-helm-chart#6]
Hello,
I was trying to install the helm chart and got the following error:
```
$  helm -f values.yaml install n8n 8gears/n8n
Error: template: n8n/templates/deployment.yaml:43:35: executing "n8n/templates/deployment.yaml" at <.Values.config>: wrong type for value; expected map[string]interface {}; got interface {}
```
The error refers to this line of code: https://github.com/8gears/n8n-helm-chart/blob/master/templates/deployment.yaml#L43

I'm not setting the `port` in my `values.yaml` so it's left commented in.

While I investigate a fix (and perhaps with a PR) I thought I'd report here first.

Happy to provide additional info if needed.

**Comment by Vad1mo** [comment]
What’s your values files look like?

**Comment by davinerd** [comment]
Here we go:
```
security:
#  excludeEndpoints: # Additional endpoints to exclude auth checks. Multiple endpoints can be separated by colon - default: ''
  basicAuth:
    active: true    # If basic auth should be activated for editor and REST-API - default: false
    user: ABC      # The name of the basic auth user - default: ''
    password: XXXXX   # The password of the basic auth user - default: ''
    hash: true      # If password for basic auth is hashed - default: false
extraEnv: {}
# Set this if running behind a reverse proxy and the external port is different from the port n8n runs on
#   WEBHOOK_TUNNEL_URL: "https://n8n.myhost.com/

persistence:
  ## If true, use a Persistent Volume Claim, If false, use emptyDir
  ##
  enabled: true
  type: dynamic # what type volume, possible options are [existing, emptyDir, dynamic] dynamic for Dynamic Volume Provisioning, existing for using an existing Claim
  storageClass: "standard"
  ## PVC annotations
  ##
  annotations:
    helm.sh/resource-policy: keep
  ## Persistent Volume Access Mode
  ##
  accessModes:
    - ReadWriteOnce
  ## Persistent Volume size
  ##
  size: 10Gi
  ## Use an existing PVC
  ##
  # existingClaim:

replicaCount: 1

image:
  repository: n8n/n8n:latest
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  }
  #hosts:
  #  - host: chart-example.local
  #    paths: []
  #tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
#   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
```
