### ISSUE TITLE
Unable to initialize DB

### ISSUE THREAD

**Issue by telekosmos** [8gears/n8n-helm-chart#67]
Hi
This is quite simple. Trying to deploy the chart by running the just the command in Readme: `helm install my-n8n oci://8gears.container-registry.com/library/n8n --version 0.20.1 -f n8n-values.yaml`. The overridden values are just:
```
# n8n-values.yaml

config:
  database:
    type: postgresdb
    postgresdb:
      database: n8n
      host: 10.109.205.83
      user: postgres
      password: '<apassword>'

secret:
  database:
    postgresdb:
      password: '<apassword>'
```
The `host` address is because in the cluster I have deployed the postgres backend and I've checked it has connectivity from other services in the cluster.

I'm clarifying about the connectivity as the issue I'm running in is just as it follows (pod logs 👇 ):
```
Loading config overwrites [ '/n8n-config/config.json', '/n8n-secret/secret.json' ]
Last session crashed
Initializing n8n process
Error: There was an error initializing DB
DatabaseError: database "n8n" does not exist
```

I'm sure I'm missing something but I can't figure out what, so appreciate any hint/suggestion.

Cheers
