### ISSUE TITLE
When scaling.webhook is enabled webhook-test paths are returning 404

### ISSUE THREAD

**Issue by aeb-dev** [8gears/n8n-helm-chart#75]
```yaml
ingress:
  enabled: true
  ...
scaling:
  enabled: true
  webhook:
    enabled: true
```
I have the configuration above for webhooks. When I deploy n8n and trigger a webhook based on test-url, I always get 404. I changed the ingress definition of `path:/webhook-test/` to use main n8n pod it works as expected.

My guess is that setting https://github.com/n8n-io/n8n/blob/master/packages/cli/src/config/schema.ts#L718 (N8N_DISABLE_PRODUCTION_MAIN_PROCESS) to true only affects the production url, so the test url should still point to main n8n
