### ISSUE TITLE
I have isolated the webhooks - production is working / test isnt / Chart: 0.23.1

### ISSUE THREAD

**Issue by egandro** [8gears/n8n-helm-chart#86]
I am using separated workers

```yml
scaling:
  enabled: true
  worker:
    count: 2
    concurrency: 2
   webhook:
     enabled: true
     count: 1
```

**Not working***

```bash
curl https://n8n.mycluster/webhook-test/test1
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /webhook-test/test1</pre>
</body>
</html>
```

**Working***

```bash
curl https://n8n.mycluster/webhook/test1
{"message":"Workflow executed successfully"}
```

** Also working **

- when I disable the webhook support

**Comment by egandro** [comment]
I am not sure if this is somehow related to my fix here: https://github.com/8gears/n8n-helm-chart/pull/59

**Comment by maozza** [comment]
the /webhook-test/ route should be pointed to the main n8n pods and not to the webhook pods. editing the ingress and **removing** the following fix the issue
```
      - backend:
          service:
            name: n8n-webhooks
            port:
              number: 80
        path: /webhook-test/
        pathType: Prefix
```
