### ISSUE TITLE
setting autoscaling.enabled to true disables the workers replicas

### ISSUE THREAD

**Issue by maozza** [8gears/n8n-helm-chart#87]
I may be missing something but when setting autoscaling.enabled to true the replicas count is not been configured

Source: https://github.com/8gears/n8n-helm-chart/blob/master/templates/deployment.worker.yaml
```
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.scaling.worker.count }}
  {{- end }}
```
The same issue with webhook deployment

**Comment by Vad1mo** [comment]
What's your config? Did you check the indentation?

**Comment by maozza** [comment]
Here is my config  (values.yaml)
Setting up **autoscaling** for the main n8n pod, disable the `replicas` for the webhook and worker.
Is the `if` statement in line 9 in `/templates/deployment.worker.yaml` and in `/templates/deployment.webhooks.yaml` is a mistake?



```
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


scaling:
  enabled: true
  worker:
    count: 10
    concurrency: 50
  # With .Values.scaling.webhook.enabled=true you disable Webhooks from the main process but you enable the processing on a different Webhook instance.
  # See https://github.com/8gears/n8n-helm-chart/issues/39#issuecomment-1579991754 for the full explanation.
  webhook:
    enabled: true
    count: 3
```
